services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - postgres
    networks:
      - trip-network

  postgres:
    image: postgres:17
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=tripplanner
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - trip-network

networks:
  trip-network:
    driver: bridge

volumes:
  postgres-data: